(define (list-of-values exps env)
  (if (no-operands? exps)
      '()
      (let ((first-value (eval (first-operand exps) env))
	    (rest-values (list-of-values (rest-operands exps) env)))
	(cons first-value rest-values))))
